---
- name: Main | Create android virtual device
  ansible.builtin.shell: >-
    echo 'no' | avdmanager create avd -f
    -n {{ item.name }}
    -k 'system-images;{{ item.android_api_level }};{{ item.api_profile }};{{ item.arch }}'{{ (['', '-d', item.device_id] | join(' ')) if 'device_id' in item else '' }}
  register: avd_manager_create_result
  changed_when: avd_manager_create_result.rc == 0

- name: Create | Override config.ini with specified properties
  ansible.builtin.lineinfile:
    path: ~/.android/avd/{{ item.name }}.avd/config.ini
    regexp: "{{ avd_property.property }}"
    line: '{{ avd_property.property }}={{ avd_property.value }}'
    state: present
  loop: "{{ item.avd_profile | d([]) + molecule_yml.driver.common_vars.avd_profile | d([]) }}"
  loop_control:
    loop_var: avd_property
