---
- name: Playbook for Android devices creation on emulator host
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Destroy | Read instance config
      ansible.builtin.set_fact:
        platforms: "{{ lookup('file', molecule_instance_config) | from_yaml }}"

    - name: Destroy | Kill emulation processes
      ansible.builtin.command: >-
        kill -9 {{ item.emulator_pid }}
      loop: "{{ platforms }}"

    - name: Destroy | Execute avdmanager delete command
      ansible.builtin.command: >-
        avdmanager delete avd -n {{ item.name }}
      loop: "{{ molecule_yml.platforms }}"
      failed_when: false

    - name: Destory | Reload adb server via common role
      ansible.builtin.import_role:
        name: reload_adb
