---
driver:
  name: molecule_adb
platforms:
  - name: molecule_sample_avd_1
    android_api_level: 'android-36'
    apis_profile: 'google_apis'
    arch: 'arm64-v8a'

  - name: molecule_sample_avd_2
    android_api_level: 'android-36'
    apis_profile: 'google_apis'
    arch: 'arm64-v8a'
