---
- name: Main | Start job with ssh server installing
  adb_termux:
    avd_port: "{{ item.port }}"
    cmd: pkg install openssh -y
  async: 600
  poll: 0
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    label: "{{ item.name }}"
  register: avd_ssh_install_jobs
  
- name: Main | Wait for all async jobs to complete
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: job_results
  until: job_results.finished
  retries: 300
  delay: 2
  loop: "{{ avd_ssh_install_jobs.results }}" # Loop over the

- name: Main | Put public ssh key to authorized_keys
  ansible.builtin.command: >-
    adb -s emulator-{{ item.port }} push
    {{ item.public_ssh_key_file }}
    /data/data/com.termux/files/home/.ssh/authorized_keys
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    label: "{{ item.name }}"

- name: Main | Change permissions for .ssh directory content
  ansible.builtin.shell: >-
    adb -s emulator-{{ item.port }} shell
    "chown -R {{ item.termux_ownership }} /data/data/com.termux/files/home/.ssh;
    chmod 700 /data/data/com.termux/files/home/.ssh;
    chmod 600 /data/data/com.termux/files/home/.ssh/authorized_keys"
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    label: "{{ item.name }}"

- name: Main | Expose ssh port to working machine
  ansible.builtin.command: >-
    adb -s emulator-{{ item.port }} forward
    tcp:{{ (item.port | int + 22) | string }}
    tcp:8022
  register: avd_ssh_port_expose_result
  changed_when: avd_ssh_port_expose_result.rc == 0
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    label: "{{ item.name }}"

- name: Main | Restart sshd daemon
  adb_termux:
    avd_port: "{{ item.port }}"
    cmd: sshd
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    label: "{{ item.name }}"
